# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing_extensions import TypeAlias

__version__ = '0.1.3'
APP_DIR: TypeAlias = __import__('pathlib').Path(__file__).resolve().parents[1]

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import pathlib
import __future__
import asyncio
import functools
import logging
import concurrent
import concurrent.futures
import concurrent.futures.ThreadPoolExecutor
import dataclasses
import typing
import datetime
import zoneinfo
import zoneinfo.ZoneInfo
import sqlalchemy
import sqlalchemy.orm
import sqlalchemy.orm.Session
import collections
import collections.abc
import sqlalchemy.create_engine
import sqlalchemy.orm.sessionmaker
import tp.APP_DIR
import re
import uuid
import contextlib
import fastapi
import fastapi.Depends
import fastapi.FastAPI
import fastapi.HTTPException
import fastapi.Query
import fastapi.responses
import fastapi.staticfiles
import tp.__version__
import httpx
import sqlalchemy.Boolean
import sqlalchemy.DateTime
import sqlalchemy.ForeignKey
import sqlalchemy.Integer
import sqlalchemy.String
import sqlalchemy.Text
import sqlalchemy.JSON
import sqlalchemy.orm.DeclarativeBase
import sqlalchemy.orm.Mapped
import sqlalchemy.orm.mapped_column
import sqlalchemy.orm.relationship
import json
import paho
import paho.mqtt
import paho.mqtt.client
import enum
import urllib
import urllib.parse
import ssl
import subprocess
import sys
import time
import pydantic
import pydantic.main
import pydantic.fields